"""models for house

Revision ID: 7cc4c5ff6b9d
Revises: c05b67d7da58
Create Date: 2022-07-07 21:47:06.449748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc4c5ff6b9d'
down_revision = 'c05b67d7da58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('House',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('is_crowd', sa.Boolean(), nullable=True),
    sa.Column('is_noisy', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('longitude', sa.Float(precision=12), nullable=True),
    sa.Column('latitude', sa.Float(precision=12), nullable=True),
    sa.Column('mount_distance', sa.Float(precision=3), nullable=True),
    sa.Column('water_distance', sa.Float(precision=3), nullable=True),
    sa.Column('forest_distance', sa.Float(precision=3), nullable=True),
    sa.Column('city_distance', sa.Float(precision=3), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_House_city_distance'), 'House', ['city_distance'], unique=False)
    op.create_index(op.f('ix_House_forest_distance'), 'House', ['forest_distance'], unique=False)
    op.create_index(op.f('ix_House_mount_distance'), 'House', ['mount_distance'], unique=False)
    op.create_index(op.f('ix_House_price'), 'House', ['price'], unique=False)
    op.create_index(op.f('ix_House_water_distance'), 'House', ['water_distance'], unique=False)
    op.create_table('HouseImage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.Text(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['house_id'], ['House.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('HousePublish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_id', sa.Integer(), nullable=True),
    sa.Column('publish_datetime', sa.DateTime(), nullable=True),
    sa.Column('vip', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['home_id'], ['House.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_HousePublish_publish_datetime'), 'HousePublish', ['publish_datetime'], unique=False)
    op.create_table('HouseComment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('send_datetime', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('house_publish_id', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['house_publish_id'], ['HousePublish.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_HouseComment_recipient_id'), 'HouseComment', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_HouseComment_sender_id'), 'HouseComment', ['sender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_HouseComment_sender_id'), table_name='HouseComment')
    op.drop_index(op.f('ix_HouseComment_recipient_id'), table_name='HouseComment')
    op.drop_table('HouseComment')
    op.drop_index(op.f('ix_HousePublish_publish_datetime'), table_name='HousePublish')
    op.drop_table('HousePublish')
    op.drop_table('HouseImage')
    op.drop_index(op.f('ix_House_water_distance'), table_name='House')
    op.drop_index(op.f('ix_House_price'), table_name='House')
    op.drop_index(op.f('ix_House_mount_distance'), table_name='House')
    op.drop_index(op.f('ix_House_forest_distance'), table_name='House')
    op.drop_index(op.f('ix_House_city_distance'), table_name='House')
    op.drop_table('House')
    # ### end Alembic commands ###
