"""empty message

Revision ID: c05b67d7da58
Revises: 
Create Date: 2022-07-03 00:05:00.908135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05b67d7da58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dialog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_datetime', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Enum('private', 'public', name='dialogtype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.String(length=24), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('send_datetime', sa.DateTime(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('on_the_way', 'delivered', 'read', name='messagestatus'), nullable=True),
    sa.Column('dialog_id', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dialog_id'], ['Dialog.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Message_recipient_id'), 'Message', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_Message_sender_id'), 'Message', ['sender_id'], unique=False)
    op.create_table('User_Dialog',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dialog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dialog_id'], ['Dialog.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User_Dialog')
    op.drop_index(op.f('ix_Message_sender_id'), table_name='Message')
    op.drop_index(op.f('ix_Message_recipient_id'), table_name='Message')
    op.drop_table('Message')
    op.drop_table('User')
    op.drop_table('Dialog')
    # ### end Alembic commands ###
